import shopify_template

def create_one_inch_row(seed: str, img_url: str):
    return {'Handle':f"special-snowflake-{seed}",
           'Title':f"{seed}",
           'Body (HTML)':"a silver snowflake, about one inch across. Each pendant is one-of-a-kind, no one else can have your snowflake.",
           'Vendor':'BaroquePlusPlus LLC',
           'Standardized Product Type':'336',
           'Custom Product Type':'',
           'Tags':"Special Snowfake, pendant, silver",
           'Published': 'TRUE',
           'Option1 Name':'Size',
           'Option1 Value': '1\'\'',
           'Option2 Name': 'Material',
           'Option2 Value': 'Sterling Silver',
           'Option3 Name':'',
           'Option3 Value':'',
           'Variant SKU':f"ss22-sv-1in-{seed}",
           'Variant Grams':0.0,
           'Variant Inventory Tracker': 'shopify',
           'Variant Inventory Qty': '1',
           'Variant Inventory Policy':'deny',
           'Variant Fulfillment Service':'manual',
           'Variant Price': 78.00,
           'Variant Compare At Price': '',
           'Variant Requires Shipping': 'TRUE',
           'Variant Taxable':'TRUE',
           'Variant Barcode':'',
           'Image Src': f"'{img_url}'",
           'Image Position': '',
           'Image Alt Text': 'A silver snowflake pendant',
           'Gift Card': 'FALSE',
           'SEO Title': 'Special Snowflake Pendant. No two are alike',
           'SEO Description': '',
           'Google Shopping / Google Product Category':'',
           'Google Shopping / Gender':'',
           'Google Shopping / Age Group':'',
           'Google Shopping / MPN':'',
           'Google Shopping / AdWords Grouping':'',
           'Google Shopping / AdWords Labels':'',
           'Google Shopping / Condition':'',
           'Google Shopping / Custom Product':'',
           'Google Shopping / Custom Label 0':'',
           'Google Shopping / Custom Label 1':'',
           'Google Shopping / Custom Label 2':'',
           'Google Shopping / Custom Label 3':'',
           'Google Shopping / Custom Label 4':'',
           'Variant Image':f"'{img_url}'",
           'Variant Weight Unit':'g',
           'Variant Tax Code':'',
           'Cost per item': 40.00,
           'Price / International': 88.00,
           'Compare At Price / International':'',
           'Status': 'active'
           }